---
- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Restart Prometheus
  service:
    name: prometheus
    state: restarted

- name: Restart Node Exporter
  service:
    name: node-exporter
    state: restarted

- name: Restart Grafana
  service:
    name: grafana-server
    state: restarted
